### ISSUE TITLE
B.Arch Sem 10 ABV report is not generating

### ISSUE THREAD

**Issue by Arushdb** [Arushdb/cms_devlopment#20]
The error occurred in in/ac/dei/edrp/cms/databasequeries/activitymaster/AwardBlankVerification.xml.
--- The error occurred while applying a parameter map.
--- Check the bulkAwardBlankVerification.insertAwardBlankErrors-InlineParameterMap.
--- Check the statement (update failed).
--- Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'semester_code' at row 1
19/06/2021 08:20:08

**Comment by Arushdb** [comment]
Please work on this issue.

**Comment by JyotiMehra7** [comment]
Problem was with semester_code length in student_error_logs table. Same has been resolved now with below DML
ALTER TABLE `student_error_logs` MODIFY COLUMN `semester_code` CHAR(5) NOT NULL;
