### ISSUE TITLE
1902955 got the remedial but in student search their SGPA of 3rd Sem is showing.

### ISSUE THREAD

**Issue by Arushdb** [Arushdb/cms_devlopment#22]
In Student Search Interface SGPA is showing in Remedial Status.

**Comment by JyotiMehra7** [comment]
Changes done to show sgpa from student registration semester header (srsh) for only PAS status else blank. 
Patch shared for implementation.

**Comment by Arushdb** [comment]
Is patch applied

**Comment by JyotiMehra7** [comment]
Patch implemented at Live now. Same has been tested and found ok.
