### ISSUE TITLE
B.tech(Part Time) Provisional Certificate is not generating

### ISSUE THREAD

**Issue by DEICMSNEW** [Arushdb/cms_devlopment#31]
Milan Ma'am reported this issue.

**Comment by JyotiMehra7** [comment]
Issue was with roll number 1906551 and so provisional report not generated. Error says div is null and entity switch case with ACT and PAS in student program. 
Same has been corrected by

**Comment by JyotiMehra7** [comment]
Respective configuration is corrected for roll number 1906551.
Provisional Certificates are now generated for B.tech (Part time).
