### ISSUE TITLE
Award blank revert should fix for Head/Dean.

### ISSUE THREAD

**Issue by DEICMSNEW** [Arushdb/cms_devlopment#37]
Award blank can be reverted by Head/Dean if award blank will be reverted till result will not be processed.

**Comment by JyotiMehra7** [comment]
To provide Withdraw Award Blank utility to Head/Dean role, changes done in Withdraw Award Blank report to populate entities based on user entity rights on this menu (MHB). 
Based on the selected session, course code, entity, instructor and pck, check whether result is processed or not. In case result is already processed then withdrawal is restricted, else internal award blank is reverted(deleted) from course_marks_approval_status. existing check of grading is commented.
Changes implemented in UAT and Live both.
